export const API_PREFIX = "/api/admin";

export const ADMIN_API_ENDPOINTS = {
  dashboardOverview: `${API_PREFIX}/dashboard/overview`,
  aiPrompts: `${API_PREFIX}/ai-prompts`,
  aiPromptDetail: (promptId: string) => `${API_PREFIX}/ai-prompts/${promptId}`,
  courses: `${API_PREFIX}/courses`,
  courseDetail: (courseId: string) => `${API_PREFIX}/courses/${courseId}`,
  courseContentWorkspace: (courseId: string) => `${API_PREFIX}/courses/${courseId}/content`,
  coursePublish: (courseId: string) => `${API_PREFIX}/courses/${courseId}/publish`,
  courseUnpublish: (courseId: string) => `${API_PREFIX}/courses/${courseId}/unpublish`,
  courseArchive: (courseId: string) => `${API_PREFIX}/courses/${courseId}/archive`,
  modules: `${API_PREFIX}/modules`,
  moduleDetail: (moduleId: string) => `${API_PREFIX}/modules/${moduleId}`,
  moduleVocabulary: (moduleId: string) => `${API_PREFIX}/modules/${moduleId}/vocabulary`,
  moduleVocabularyDetail: (vocabularyId: string) => `${API_PREFIX}/module-vocabulary/${vocabularyId}`,
  lessons: `${API_PREFIX}/lessons`,
  lessonDetail: (lessonId: string) => `${API_PREFIX}/lessons/${lessonId}`,
  lessonRead: (lessonId: string) => `${API_PREFIX}/lessons/${lessonId}/read`,
  lessonWrite: (lessonId: string) => `${API_PREFIX}/lessons/${lessonId}/write`,
  lessonVideo: (lessonId: string) => `${API_PREFIX}/lessons/${lessonId}/video`,
  lessonQuiz: (lessonId: string) => `${API_PREFIX}/lessons/${lessonId}/quiz`,
  lessonVocabulary: (lessonId: string) => `${API_PREFIX}/lessons/${lessonId}/vocabulary`,
  lessonVocabularyDetail: (vocabularyId: string) => `${API_PREFIX}/lesson-vocabulary/${vocabularyId}`,
  orders: `${API_PREFIX}/orders`,
  orderAnalytics: `${API_PREFIX}/orders/analytics`,
  orderApprove: (orderId: string) => `${API_PREFIX}/orders/${orderId}/approve`,
  orderReject: (orderId: string) => `${API_PREFIX}/orders/${orderId}/reject`,
  transactionLogs: `${API_PREFIX}/orders/transaction-logs`,
  reviews: `${API_PREFIX}/reviews`,
  reviewReply: (reviewId: string) => `${API_PREFIX}/reviews/${reviewId}/reply`,
  reviewStatus: (reviewId: string) => `${API_PREFIX}/reviews/${reviewId}/status`,
} as const;
